apiVersion: v1
kind: Service
metadata:
  name: anime-frontend-service
spec:
  selector:
    app: animefrontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 3001
  type: NodePort
